"""
Generate a LARGE fleet of demo cars so the admin Cars table can be seen at real
scale (search + GPS filter + pagination). Gives a handful of companies 100+ cars
each, plus mid-size fleets, so paging / filtering is exercised. Writes
seed_cars_bulk.sql.

Re-runnable: every car carries a 'DMO' VIN prefix; the SQL first deletes those
then reinserts. Only touches DMO-prefixed cars, so real/other seed cars survive.

Run:  backend\\.venv\\Scripts\\python.exe gen_cars_seed.py
Load: docker exec -i carrental-postgres psql -U postgres -d carrental < backend/seed_cars_bulk.sql
"""
import random

random.seed(7)  # reproducible

# Companies (by companyid) that should get a big fleet, and how many cars each.
# Mix of large (100+) and medium so the table + pager are exercised realistically.
FLEETS = {
    "DEMO-001": 160, "DEMO-002": 140, "DEMO-003": 120, "DEMO-004": 100,
    "DEMO-005": 85,  "DEMO-006": 60,  "DEMO-007": 45,  "DEMO-008": 30,
    "DEMO-009": 18,  "DEMO-010": 12,
}

# body types
TYPES = ["Sedan", "SUV", "Hatchback", "Pickup", "Van", "Coupe", "Crossover"]

# make/model pool
MODELS = [
    "Toyota Corolla", "Toyota Camry", "Toyota RAV4", "Toyota Yaris",
    "Honda Civic", "Honda Accord", "Honda CR-V", "Nissan Sunny",
    "Nissan Altima", "Nissan Kicks", "Hyundai Elantra", "Hyundai Tucson",
    "Hyundai Accent", "Kia Sportage", "Kia Rio", "Kia Cerato",
    "Mercedes C-Class", "Mercedes E-Class", "BMW 3 Series", "BMW X5",
    "Volkswagen Golf", "Volkswagen Passat", "Ford Focus", "Ford Explorer",
    "Chevrolet Malibu", "Chevrolet Tahoe", "Peugeot 208", "Renault Clio",
    "Mazda 3", "Mazda CX-5", "Mitsubishi Lancer", "Jeep Wrangler",
]

# colors that have swatches in the UI
COLORS = ["White", "Black", "Silver", "Gray", "Red", "Blue", "Green", "Beige"]

# VIN charset excludes I, O, Q (real-VIN rule). We prefix with 'DMO' for cleanup.
VIN_CHARS = "ABCDEFGHJKLMNPRSTUVWXYZ0123456789"

# Lebanese-style plate letters
PLATE_LETTERS = "ABGKMNSTZ"

used_vins = set()
used_plates = set()


def make_vin():
    while True:
        v = "DMO" + "".join(random.choice(VIN_CHARS) for _ in range(14))
        if v not in used_vins:
            used_vins.add(v)
            return v


def make_plate():
    while True:
        p = f"{random.choice(PLATE_LETTERS)} {random.randint(100000, 999999)}"
        if p not in used_plates:
            used_plates.add(p)
            return p


rows = []  # (cid, vin, type, model, color, plate, has_gps)
for cid, n in FLEETS.items():
    for _ in range(n):
        rows.append((
            cid,
            make_vin(),
            random.choice(TYPES),
            random.choice(MODELS),
            random.choice(COLORS),
            make_plate(),
            "true" if random.random() < 0.55 else "false",
        ))

lines = []
lines.append("-- =====================================================")
lines.append("-- BULK DEMO CARS — large per-company fleets for the admin Cars table.")
lines.append(f"-- {len(rows)} cars across {len(FLEETS)} companies. Generated by gen_cars_seed.py.")
lines.append("-- Re-runnable: DMO-prefixed VINs are deleted then reinserted.")
lines.append("-- Load: docker exec -i carrental-postgres psql -U postgres -d carrental < backend/seed_cars_bulk.sql")
lines.append("-- =====================================================")
lines.append("BEGIN;")
lines.append("DELETE FROM cars WHERE vin LIKE 'DMO%';")
lines.append("INSERT INTO cars (vin, type, model, color, platenumber, has_gps, company_id)")
lines.append("SELECT v.vin, v.type, v.model, v.color, v.plate, v.has_gps,")
lines.append("       (SELECT id FROM companies WHERE companyid = v.cmp)")
lines.append("FROM (VALUES")
vals = [
    f"  ('{r[0]}', '{r[1]}', '{r[2]}', '{r[3]}', '{r[4]}', '{r[5]}', {r[6]})"
    for r in rows
]
lines.append(",\n".join(vals))
lines.append(") AS v(cmp, vin, type, model, color, plate, has_gps)")
lines.append("WHERE EXISTS (SELECT 1 FROM companies WHERE companyid = v.cmp);")
lines.append("")
lines.append("-- Base each demo car at a random active branch of its own company (~85%);")
lines.append("-- the rest stay at Main. Requires migration 031 (cars.branch_id).")
lines.append("UPDATE cars c")
lines.append("SET branch_id = (")
lines.append("  SELECT b.id FROM branches b")
lines.append("  WHERE b.company_id = c.company_id AND b.is_active = TRUE")
lines.append("  ORDER BY random() LIMIT 1)")
lines.append("WHERE c.vin LIKE 'DMO%' AND random() < 0.85;")
lines.append("COMMIT;")
lines.append("")
lines.append("SELECT co.companyid, co.companyname, COUNT(c.id) AS cars")
lines.append("FROM companies co JOIN cars c ON c.company_id = co.id AND c.is_active")
lines.append("WHERE c.vin LIKE 'DMO%'")
lines.append("GROUP BY co.companyid, co.companyname ORDER BY cars DESC;")

with open("seed_cars_bulk.sql", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"wrote seed_cars_bulk.sql — {len(rows)} cars across {len(FLEETS)} companies")
